import Link from 'next/link';
import { launchConfig } from '../launch-config';

function Status({ live = false }: { live?: boolean }) {
  return <span className={`statusBadge ${live ? 'live' : ''}`}>{live ? 'SUPPORTED' : 'PLANNED'}</span>;
}

export default function DocsPage() {
  const mintConfigured = Boolean(launchConfig.config);
  const sections = ['overview', 'economics', 'launch-pass', 'launches', 'holder-drops', 'pump-rail', 'compare', 'ipo-token', 'signal', 'activity', 'disclosures', 'faq'];
  return <main className="docsPage">
    <header className="siteHeader"><Link className="wordmark" href="/"><span>IPO</span><small>PUBLIC DOCS</small></Link><nav><Link href="/">Explore</Link><a href="#economics">Economics</a><a href="#disclosures">Disclosures</a></nav><Link className="walletControl" href="/">Back to app</Link></header>
    <header className="docsHero"><p className="kicker">Initial Pump Offering</p><h1>Launch terms without the fog.</h1><p>Confirmed Launch Pass economics, proposed project-token launch mechanics, integration status, and the receipts required before any financial claim goes live.</p></header>
    <div className="docsLayout"><aside className="docsNav">{sections.map((section) => <a href={`#${section}`} key={section}>{section.replaceAll('-', ' ')}</a>)}</aside><article className="docsContent">
      <section id="overview"><p className="kicker">Overview</p><h2>A curated Solana launch and discovery platform.</h2><p>IPO is designed for project teams preparing high-quality fair launches and for communities that want clearer research, launch terms, holder drops, and on-chain receipts. It is not an issuer-backed pre-IPO securities platform, a broker, or a promise of company shares.</p><div className="statusRows"><div><Status live /><p>Dark product experience, deterministic Launch Pass art, documentation, wallet connection, and transaction-state handling.</p></div><div><Status live={mintConfigured} /><p>{mintConfigured ? 'Public pass mint configuration is present and checked against the expected economics.' : 'Mint program source and client exist, but public on-chain configuration is missing.'}</p></div><div><Status /><p>Project intake, review, Pump.fun launch integration, comparisons, holder-drop contracts, IPO claims, activity indexing, Signal campaigns, and buyback/burn automation.</p></div></div></section>
      <section id="economics"><p className="kicker">Confirmed defaults</p><h2>1,212 passes at 0.044 SOL.</h2><div className="statusRows"><div><strong>Supply</strong><p>1,212 numbered Metaplex Core Launch Passes.</p></div><div><strong>Mint</strong><p>0.044 SOL per pass, plus separately disclosed network and account costs.</p></div><div><strong>IPO token</strong><p>No IPO is required, locked, or burned during minting. IPO is reserved for optional post-mint use.</p></div><div><strong>Sellout gross</strong><p>53.328 SOL before network, account, hosting, operational, tax, and other costs.</p></div></div></section>
      <section id="launch-pass"><p className="kicker">Launch Pass</p><h2>Membership, not a guaranteed return.</h2><p>A successful mint creates a transferable Metaplex Core asset with a persistent serial and visual level. The proposed holder product includes project previews, eligibility for funded project-token drops, watchlists, contribution history, claims, and receipts.</p><p>Essential ownership, claim, receipt, and disclosure access remains available without upgrading. Five optional visual and research-tool levels are proposed; prices and payments remain disabled.</p><Status live={mintConfigured} /></section>
      <section id="launches"><p className="kicker">Launch review</p><h2>Apply, review, fund, launch, verify.</h2><p>Project intake is proposed as a reviewed process rather than an automatic listing. Before a project can appear as upcoming or open, it should publish its team or responsible party, token address when created, supply, launch rail, holder reserve, timing, risks, links, moderation status, and cancellation treatment.</p><p>No launch currently appears as approved, funded, or live. Research entries must remain visually separate from executable opportunities.</p><Status /></section>
      <section id="holder-drops"><p className="kicker">Project-funded holder drops</p><h2>{launchConfig.holderPoolPercent}% or 10% templates, selected per launch.</h2><p>An approved project may propose a standard {launchConfig.holderPoolPercent}% reserve or featured 10% reserve of its project-token supply for eligible Launch Pass holders. These are templates, not automatic rights. A project must choose the amount, deposit the exact tokens, and publish eligibility, snapshot, weighting, vesting, rounding, claim conditions, and unclaimed-token treatment before the round opens.</p><p>The first release should use equal base weight per eligible pass. No upgrade multiplier or “booster” allocation is active. Any future booster policy requires separate review and explicit per-launch disclosure.</p><Status /></section>
      <section id="pump-rail"><p className="kicker">Pump.fun launch rail</p><h2>Preparation on IPO, token creation through Pump.</h2><p>The proposed integration sends selected project launches through Pump.fun and tracks the resulting token and canonical market. Pump.fun currently supports SOL- or USDC-denominated launches; the repository does not support pairing a launch directly with the PUMP token. Successful bonding curves graduate automatically to a canonical PumpSwap pool.</p><p>IPO does not currently create Pump.fun coins, route trades, collect creator fees, or control PumpSwap liquidity.</p><Status /></section>
      <section id="compare"><p className="kicker">IPO Compare</p><h2>Address-based token comparison.</h2><p>The proposed comparison surface uses exact Solana addresses and timestamped sources to show price, liquidity, holder concentration, launch source, contract signals, and disclosed launch terms. No market-data adapter is connected, so comparison inputs remain disabled and unavailable values are never shown as zero.</p><Status /></section>
      <section id="ipo-token"><p className="kicker">IPO token</p><h2>Optional ecosystem use after mint.</h2><p>A future IPO token may be launched through Pump.fun. A separate genesis claim for verified Launch Pass holders is proposed, but token amount, snapshot, exclusions, vesting, claim authority, and contract are unresolved. Holding a pass does not currently create an IPO-token entitlement.</p><p>A future policy may direct a disclosed portion of realized platform revenue to open-market IPO purchases and token burns. This is not revenue sharing, a dividend, a holder payment, or a promise of price support. The percentage is unset, and each purchase and burn must be proven on-chain.</p><Status /></section>
      <section id="signal"><p className="kicker">IPO Signal</p><h2>Reviewed contribution, not engagement farming.</h2><p>Proposed campaigns can accept original research, educational explainers, thoughtful launch coverage, creative campaign assets, community answers, and product feedback. Every campaign needs an objective, deadline, eligibility rules, reviewer, funded reward, moderation, and anti-abuse review.</p><p>No follower-count leaderboard, automatic rewards for likes, spam missions, or paid price promotion. Contribution credit may unlock nonfinancial tools or cosmetics after a policy is published; it does not increase allocation weight.</p><Status /></section>
      <section id="activity"><p className="kicker">Activity</p><h2>One ledger, distinct financial states.</h2><p>The activity layer will separately record launch creation, reserve funding, snapshot finalization, allocation, claim, creator-fee receipt, IPO purchase, token burn, cancellation, and refund. A connected wallet, requested signature, social post, or announced policy is not proof of completion.</p><Status /></section>
      <section id="disclosures"><p className="kicker">Disclosures</p><h2>Project tokens are not company stock.</h2><p>IPO currently supports a Launch Pass concept and proposed project-token launch workflows. It does not provide substantiated issuer-backed pre-IPO securities inventory. “IPO” means Initial Pump Offering in this product and must not be interpreted as a regulated public offering.</p><p>No launch, allocation, drop, listing, liquidity, buyback, burn, dollar value, return, or availability is guaranteed. Token launches and trading carry substantial risk.</p></section>
      <section id="faq"><p className="kicker">FAQ</p><h2>Short answers.</h2><div className="faqList"><article><h3>Can I mint now?</h3><p>{mintConfigured ? 'The site has a public configuration and verifies its economics before enabling mint.' : 'No. The public on-chain configuration is missing, so the interface remains in preview mode.'}</p></article><article><h3>Do I need IPO to mint?</h3><p>No. Minting is 0.044 SOL plus network and account costs.</p></article><article><h3>Does every project owe holders 10%?</h3><p>No. The {launchConfig.holderPoolPercent}% and 10% reserves are proposed templates. A project must select, fund, and disclose its own round before any eligibility exists.</p></article><article><h3>Is IPO paired with PUMP?</h3><p>No. Pump.fun documents SOL and USDC launch pairs. No PUMP pair or Pump integration is implemented here.</p></article><article><h3>Are buybacks guaranteed?</h3><p>No. The policy, revenue percentage, contracts, and wallets are not finalized.</p></article><article><h3>Is this company equity?</h3><p>No. The current product concerns NFTs and project tokens, not company shares.</p></article></div></section>
    </article></div>
  </main>;
}
