import { mintEnvironmentConfigured, publicMintConfigured } from "../launch-config";
import { compatibilityRules, traitCategories, traitCount } from "../pumpio-data";

function State({ children, kind = "preview" }: { children: React.ReactNode; kind?: "live" | "preview" | "blocked" }) {
  return <span className={`pioDocState ${kind}`}>{children}</span>;
}

export default function DocsPage() {
  const sections = ["overview", "pumpios", "traits", "wallets", "accounts", "mint", "leveling", "access", "rewards", "launchpad", "proof", "migration", "risks"];
  return (
    <main className="pioDocs">
      <header><p className="pioEyebrow">IPO DOCUMENTATION</p><h1>THE OFFERING, IN PLAIN ENGLISH.</h1><p>What the protocol does, what a Pumpio provides, which money flows are only proposed, and exactly what blocks production transactions.</p></header>
      <div className="pioDocsLayout">
        <aside>{sections.map((section) => <a href={`#${section}`} key={section}>{section}</a>)}</aside>
        <article>
          <section id="overview"><p className="pioEyebrow">OVERVIEW</p><h2>IPO means Initial Pump Offering.</h2><p>IPO is a Solana launchpad for structured presale preparation, fair launches, offering research, and transparent creator-fee routing. PUMPIOS are the limited collectible membership layer. $IPO is the intended protocol token. PUMP is an intended reward or paired ecosystem asset only where exact addresses, routes, and distribution infrastructure are verified.</p><p>Project tokens are not company IPO shares or company equity.</p><State kind="live">FRONTEND LIVE</State></section>
          <section id="pumpios"><p className="pioEyebrow">PUMPIOS</p><h2>1,200 target Core NFTs.</h2><div className="pioDocRows"><div><strong>Supply</strong><p>1,200 intended Pumpios. The previous source used 1,212 and requires migration.</p></div><div><strong>Participation</strong><p>One Pumpio equals one base participation unit where a funded program defines Pumpio eligibility.</p></div><div><strong>Art</strong><p>Capsule-headed underwriters using a hand-drawn visual language: irregular ink, graphite, gouache, halftone, and paper grain. Preview images were produced with generative image tools under human art direction.</p></div><div><strong>Metadata</strong><p>Nine approved V3 concepts and a deterministic 1,200-item draft trait blueprint exist. Final rendered images and metadata are not frozen.</p></div></div><State kind="preview">V3 ART SYSTEM READY</State> <State kind="blocked">COLLECTION DEPLOYMENT REQUIRED</State></section>
          <section id="traits"><p className="pioEyebrow">TRAITS</p><h2>{traitCount} documented traits across {traitCategories.length} families.</h2><p>The draft catalog covers capsule material, expression, eyes, outfit, headwear, eyewear, held items, neckwear, background, market artifacts, surface treatment, and status details. All 1,200 draft signatures regenerate from a stable seed and are checked for exact duplicates.</p><div className="pioDocRows">{traitCategories.map((category) => <div key={category.id}><strong>{category.label} / {category.count}</strong><p>{Object.values(category.values).flat().slice(0, 5).join(", ")}.</p></div>)}</div><p>{compatibilityRules.join(" ")}</p><State kind="live">DETERMINISTIC BLUEPRINT TESTED</State> <State kind="preview">ART METADATA DRAFT</State></section>
          <section id="wallets"><p className="pioEyebrow">WALLETS</p><h2>Connect, inspect, disconnect.</h2><p>The frontend detects compatible injected Solana wallets, presents available providers, follows account changes, and supports explicit disconnect. Connecting is free and does not authorize a transaction. Every mint or launch action must still be reviewed and approved inside the selected wallet.</p><p>IPO never asks for seed phrases or private keys. A production transaction is not successful until chain confirmation and resulting account state are verified.</p><State kind="live">WALLET CONNECTION UI LIVE</State></section>
          <section id="accounts"><p className="pioEyebrow">CREATOR ACCOUNTS</p><h2>Links are not identity verification.</h2><p>The launch builder accepts website, X profile, and Telegram links in a local draft. X OAuth, verified ownership, team authentication, server-side profiles, and publishing permissions are not connected. IPO never posts automatically.</p><State kind="live">LOCAL SOCIAL LINKS WORK</State> <State kind="blocked">X OAUTH BACKEND REQUIRED</State></section>
          <section id="mint"><p className="pioEyebrow">MINT</p><h2>0.12 SOL. No $IPO requirement.</h2><p>The intended mint creates one Metaplex Core Pumpio. The full 0.12 SOL is routed to that NFT&apos;s mint-funded asset capital in the revised source. Network and account costs are separate. Mint capital is not revenue, yield, a redemption guarantee, or guaranteed value.</p><p>The client checks executable program state, exact 1,200 supply, price, config ownership, collection ownership, pause state, metadata URL, published addresses, and an explicit public-release switch before enabling a transaction.</p><State kind={publicMintConfigured ? "preview" : "blocked"}>{publicMintConfigured ? "ON-CHAIN VERIFICATION REQUIRED" : mintEnvironmentConfigured ? "PUBLIC RELEASE SWITCH OFF" : "ADDRESSES NOT PUBLISHED"}</State></section>
          <section id="leveling"><p className="pioEyebrow">LEVELING</p><h2>Intern to Chairman.</h2><p>The intended progression has ten levels: Intern, Analyst, Associate, Trader, Broker, Underwriter, Market Maker, Bookrunner, Partner, and Chairman. The previous source exposed five upgrade steps; the shared local configuration now targets ten. Upgrade prices are unset and payments are disabled.</p><p>Future upgrades may improve art, alerts, organization, analytics, exports, and personalization. Basic holdings, claims, receipts, and disclosures remain available without upgrading.</p><State kind="blocked">UPGRADE MIGRATION REQUIRED</State></section>
          <section id="access"><p className="pioEyebrow">HOLDER ACCESS</p><h2>Offering-specific, funded, and disclosed.</h2><p>No universal 3.3% allocation exists in the current contract. A future offering may reserve a purchase tranche, free distribution, or application privilege for Pumpios, but it must label the benefit precisely and publish its funding, snapshot cutoff, allocation method, vesting, claim rules, and unclaimed treatment.</p><p>Leveling does not multiply base economic participation in the current product policy.</p><State>ARCHITECTURE ONLY</State></section>
          <section id="rewards"><p className="pioEyebrow">REWARDS</p><h2>Revenue received is not revenue promised.</h2><p>The intended flow is verified IPO revenue to a disclosed combination of PUMP purchases and Pumpio distributions, $IPO buyback and burn, and continued development. Final percentages are not set. The exact PUMP mint and pair are not published.</p><p>Before activation IPO needs verified token addresses, swap routes, revenue custody, ownership snapshots, exclusions, allocation rules, distribution or claim infrastructure, retries, and receipts.</p><div className="pioDocRows"><div><strong>PUMP holder rewards</strong><p>Not active.</p></div><div><strong>$IPO buyback + burn</strong><p>Not active.</p></div><div><strong>Treasury share</strong><p>Policy not finalized.</p></div><div><strong>Reward ledger</strong><p>No production indexer.</p></div></div><State kind="blocked">NOT ACTIVE</State></section>
          <section id="launchpad"><p className="pioEyebrow">LAUNCHPAD</p><h2>Presale preparation and fair-launch tooling.</h2><p>The launch builder stores a project draft locally, previews project media, records social links, supports SOL or USDC quote selection, validates a customizable creator-fee split at exactly 100%, and exports a portable launch brief. Pump execution, fee finalization, metadata upload, and post-transaction verification are not connected.</p><p>Current Pump documentation describes creator-fee sharing through a sharing configuration and graduation to PumpSwap. IPO must integrate the official program and read the resulting sharing state before calling a launch configured. Curated presale deposits remain disabled until segregated escrow, caps, cancellation, settlement, and refunds are implemented and reviewed.</p><p><a href="https://github.com/pump-fun/pump-public-docs/blob/main/docs/instructions/CREATOR_FEE_SHARING.md" rel="noreferrer" target="_blank">Official Pump creator-fee sharing documentation</a></p><p>A saved or exported draft is not a launched token. IPO will not show fake raise totals, volume, participants, or countdowns.</p><State kind="live">CUSTOMIZABLE LOCAL DRAFTING WORKS</State> <State kind="blocked">FINANCIAL EXECUTION BLOCKED</State></section>
          <section id="proof"><p className="pioEyebrow">PROOF</p><h2>Everything on the books.</h2><p>Production proof must include the mint program/config, Core collection, $IPO token, PUMP pair, offering contracts, revenue receipts, purchases, snapshots, Pumpio distributions, and $IPO burns. A wallet connection is not a receipt, and a signature is not completion.</p><State>PROOF UI READY</State></section>
          <section id="migration"><p className="pioEyebrow">REQUIRED MIGRATION</p><h2>Frontend intent does not change a deployed contract.</h2><ol><li>Finalize all 1,200 Pumpio artworks and metadata.</li><li>Review the revised ten-level Anchor source and account semantics.</li><li>Create the Metaplex Core collection under the correct authority.</li><li>Deploy and initialize the revised program/config on devnet.</li><li>Test mint, pause, sold-out, rejection, insufficient funds, upgrades, and metadata updates.</li><li>Review security and authority policy.</li><li>Publish the complete mainnet address set and pass read-only preflight.</li></ol><State kind="blocked">PRODUCTION MINT BLOCKED</State></section>
          <section id="risks"><p className="pioEyebrow">RISK DISCLOSURES</p><h2>No guaranteed return, access, or liquidity.</h2><p>Pumpios do not represent company shares, principal protection, a cash floor, guaranteed allocation, guaranteed rewards, guaranteed resale, or guaranteed project acceptance. Any third-party asset requires exact identity, rights, controls, liquidity, and execution review.</p></section>
        </article>
      </div>
    </main>
  );
}
