skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program = "9Gqg4yjDH34pgMXRTqxdJFbzvzeBBDkGvaJvb9kKRaPU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
